name: Update Files

on:
  push:
    branches:
      - master  # Change this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Execute Script
        run: |
          python toc_generator.py
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update TOC
